# Generated by Django 4.2.5 on 2023-10-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontapp', '0003_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Total_Price',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
